
dataset_attributes:
  annotations:
    train: /data2/npl/ViInfographicCaps/data/data/paddle_ocr_description/train_new.json
    val: /data2/npl/ViInfographicCaps/data/data/paddle_ocr_description/val_new.json
    test: /data2/npl/ViInfographicCaps/data/data/paddle_ocr_description/test_new.json
model_attributes:
  hidden_size: 768
  pretrained: /data2/npl/ViInfographicCaps/model/vit5-large
  max_input_length: 128
  max_target_length: 50

training_parameters:
  do_train: True
  do_eval: False
  num_train_epochs: 40
  learning_rate: 1e-5
  warmup_ratio: 0.05
  weight_decay: 0.01
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 64
  logging_dir: './save/logging'
  group_by_length: True
  save_strategy: epoch
  save_total_limit: 3
  fp16: True
optimizer:
  lr: 1e-3,
  eps: (1e-30, 1e-3),
  clip_threshold: 1.0,
  decay_rate: -0.8,
  beta1: None,
  weight_decay: 0.0,
  relative_step: False,
  scale_parameter: False,
  warmup_init: False


    